<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UserSecretsId>fe011512-f1d3-4dda-a46f-d296d7c1a26e</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="CassandraCSharpDriver" Version="3.22.0" />
    <PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer" Version="10.0.0" />
    <PackageReference Include="Microsoft.AspNetCore.OpenApi" Version="10.0.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\ScalableChat.Common\ScalableChat.Common.csproj" />
    <ProjectReference Include="..\ScalableChat.ServiceDefaults\ScalableChat.ServiceDefaults.csproj" />
  </ItemGroup>

</Project>
