version: '3.8'

services:
  scylla-node1:
    image: scylladb/scylla:latest
    container_name: scylla-node1
    command: --seeds=scylla-node1
    ports:
      - "9042:9042"
    volumes:
      - scylla_node1_data:/var/lib/scylla
    networks:
      - scylla-net

  cqlsh:
    image: nuvo/docker-cqlsh
    container_name: scylla-cqlsh
    depends_on:
      - scylla-node1
    entrypoint: [ "sh", "-c", "sleep 10 && cqlsh scylla-node1 9042" ]
    networks:
      - scylla-net
    tty: true
    stdin_open: true

  init-cql:
    image: nuvo/docker-cqlsh
    depends_on:
      - scylla-node1
    volumes:
      - ./init.cql:/init.cql
    entrypoint: [ "sh", "-c", "sleep 20 && cqlsh scylla-node1 9042 -f /init.cql" ]
    networks:
      - scylla-net
      
volumes:
  scylla_node1_data:
  scylla_node2_data:
  scylla_node3_data:

networks:
  scylla-net:
