<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UserSecretsId>8b6d43ee-8538-4fc1-b8ca-5f9aedf92cf3</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Aspire.Confluent.Kafka" Version="9.5.1" />
    <PackageReference Include="Aspire.StackExchange.Redis" Version="9.5.1" />
    <PackageReference Include="Microsoft.AspNetCore.OpenApi" Version="9.0.10" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\ScalableChat.Common\ScalableChat.Common.csproj" />
    <ProjectReference Include="..\ScalableChat.ServiceDefaults\ScalableChat.ServiceDefaults.csproj" />
  </ItemGroup>

</Project>
